// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUsersRed = `-- name: UpdateUsersRed :exec
UPDATE users SET is_chirpy_red = true where id = $1
`

func (q *Queries) UpdateUsersRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUsersRed, id)
	return err
}
