// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_refresh.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefresh = `-- name: CreateRefresh :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES ($1, NOW(), NOW(), $2, $3)
RETURNING token, created_at, updated_at, expires_at, revoked_at, user_id
`

type CreateRefreshParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefresh(ctx context.Context, arg CreateRefreshParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefresh, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}
