// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: del_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const delChirp = `-- name: DelChirp :exec

delete from chirps where id = $1
`

func (q *Queries) DelChirp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delChirp, id)
	return err
}
