// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hash_pass.sql

package database

import (
	"context"
	"database/sql"
)

const hashPass = `-- name: HashPass :one
SELECT hashed_password from users where email = $1
`

func (q *Queries) HashPass(ctx context.Context, email string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, hashPass, email)
	var hashed_password sql.NullString
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
