// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_pass_email.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updatePassEmail = `-- name: UpdatePassEmail :one
update users set email = $3, hashed_password = $2 where id = $1
returning id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdatePassEmailParams struct {
	ID             uuid.UUID
	HashedPassword sql.NullString
	Email          string
}

func (q *Queries) UpdatePassEmail(ctx context.Context, arg UpdatePassEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePassEmail, arg.ID, arg.HashedPassword, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
