// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_password.sql

package database

import (
	"context"
)

const userPassword = `-- name: UserPassword :one
SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users where email = $1
`

func (q *Queries) UserPassword(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userPassword, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
